const achievements = [
  // ===== GETTING STARTED (Easy) =====
  {
    id: "first_steps",
    title: "First Steps",
    description: "Complete your first lesson",
    category: "getting_started",
    difficulty: "easy",
    icon: "Play",
    xpReward: 10,
    fdrReward: 0,
    condition: { type: "lessonsCompleted", value: 1 },
  },
  {
    id: "welcome_aboard",
    title: "Welcome Aboard",
    description: "Enroll in your first course",
    category: "getting_started",
    difficulty: "easy",
    icon: "BookOpen",
    xpReward: 10,
    fdrReward: 0,
    condition: { type: "coursesEnrolled", value: 1 },
  },
  {
    id: "profile_complete",
    title: "Identity Established",
    description: "Complete your profile with bio and avatar",
    category: "getting_started",
    difficulty: "easy",
    icon: "User",
    xpReward: 15,
    fdrReward: 0,
    condition: { type: "profileComplete" },
  },

  // ===== LEARNING STREAKS (Easy - Legendary) =====
  {
    id: "three_day_streak",
    title: "Getting Consistent",
    description: "Maintain a 3-day learning streak",
    category: "streaks",
    difficulty: "easy",
    icon: "Flame",
    xpReward: 25,
    fdrReward: 0.5,
    condition: { type: "currentStreak", value: 3 },
  },
  {
    id: "week_warrior",
    title: "Week Warrior",
    description: "Maintain a 7-day learning streak",
    category: "streaks",
    difficulty: "medium",
    icon: "Flame",
    xpReward: 50,
    fdrReward: 1,
    condition: { type: "currentStreak", value: 7 },
  },
  {
    id: "two_week_champion",
    title: "Two Week Champion",
    description: "Maintain a 14-day learning streak",
    category: "streaks",
    difficulty: "hard",
    icon: "Flame",
    xpReward: 100,
    fdrReward: 2,
    condition: { type: "currentStreak", value: 14 },
  },
  {
    id: "marathon_runner",
    title: "Marathon Runner",
    description: "Maintain a 30-day learning streak",
    category: "streaks",
    difficulty: "extreme",
    icon: "Zap",
    xpReward: 250,
    fdrReward: 5,
    condition: { type: "currentStreak", value: 30 },
  },
  {
    id: "streak_master",
    title: "Streak Master",
    description: "Maintain a 60-day learning streak",
    category: "streaks",
    difficulty: "extreme",
    icon: "Zap",
    xpReward: 500,
    fdrReward: 10,
    condition: { type: "currentStreak", value: 60 },
  },
  {
    id: "streak_legend",
    title: "Streak Legend",
    description: "Maintain a 100-day learning streak",
    category: "streaks",
    difficulty: "legendary",
    icon: "Crown",
    xpReward: 1000,
    fdrReward: 20,
    condition: { type: "currentStreak", value: 100 },
  },
  {
    id: "streak_immortal",
    title: "Streak Immortal",
    description: "Maintain a 365-day learning streak",
    category: "streaks",
    difficulty: "legendary",
    icon: "Crown",
    xpReward: 5000,
    fdrReward: 100,
    condition: { type: "currentStreak", value: 365 },
  },

  // ===== COURSE COMPLETION (Easy - Legendary) =====
  {
    id: "course_conqueror",
    title: "Course Conqueror",
    description: "Complete your first course",
    category: "completion",
    difficulty: "easy",
    icon: "Trophy",
    xpReward: 100,
    fdrReward: 2,
    condition: { type: "completedCourses", value: 1 },
  },
  {
    id: "triple_threat",
    title: "Triple Threat",
    description: "Complete 3 courses",
    category: "completion",
    difficulty: "easy",
    icon: "Target",
    xpReward: 150,
    fdrReward: 3,
    condition: { type: "completedCourses", value: 3 },
  },
  {
    id: "knowledge_seeker",
    title: "Knowledge Seeker",
    description: "Complete 5 courses",
    category: "completion",
    difficulty: "medium",
    icon: "Brain",
    xpReward: 250,
    fdrReward: 5,
    condition: { type: "completedCourses", value: 5 },
  },
  {
    id: "academic_achiever",
    title: "Academic Achiever",
    description: "Complete 10 courses",
    category: "completion",
    difficulty: "hard",
    icon: "GraduationCap",
    xpReward: 500,
    fdrReward: 10,
    condition: { type: "completedCourses", value: 10 },
  },
  {
    id: "dedicated_learner",
    title: "Dedicated Learner",
    description: "Complete 15 courses",
    category: "completion",
    difficulty: "hard",
    icon: "BookOpen",
    xpReward: 750,
    fdrReward: 15,
    condition: { type: "completedCourses", value: 15 },
  },
  {
    id: "master_learner",
    title: "Master Learner",
    description: "Complete 25 courses",
    category: "completion",
    difficulty: "extreme",
    icon: "Award",
    xpReward: 1000,
    fdrReward: 25,
    condition: { type: "completedCourses", value: 25 },
  },
  {
    id: "knowledge_vault",
    title: "Knowledge Vault",
    description: "Complete 35 courses",
    category: "completion",
    difficulty: "extreme",
    icon: "Shield",
    xpReward: 1500,
    fdrReward: 35,
    condition: { type: "completedCourses", value: 35 },
  },
  {
    id: "legend_scholar",
    title: "Legend Scholar",
    description: "Complete 50 courses",
    category: "completion",
    difficulty: "legendary",
    icon: "Crown",
    xpReward: 2500,
    fdrReward: 50,
    condition: { type: "completedCourses", value: 50 },
  },
  {
    id: "grand_master",
    title: "Grand Master",
    description: "Complete 75 courses",
    category: "completion",
    difficulty: "legendary",
    icon: "Crown",
    xpReward: 4000,
    fdrReward: 80,
    condition: { type: "completedCourses", value: 75 },
  },
  {
    id: "ultimate_scholar",
    title: "Ultimate Scholar",
    description: "Complete 100 courses",
    category: "completion",
    difficulty: "legendary",
    icon: "Crown",
    xpReward: 10000,
    fdrReward: 200,
    condition: { type: "completedCourses", value: 100 },
  },

  // ===== WATCH TIME (Easy - Extreme) =====
  {
    id: "first_hour",
    title: "First Hour",
    description: "Watch 1 hour of content",
    category: "watch_time",
    difficulty: "easy",
    icon: "Clock",
    xpReward: 10,
    fdrReward: 0,
    condition: { type: "totalWatchTime", value: 3600 },
  },
  {
    id: "binge_watcher",
    title: "Binge Watcher",
    description: "Watch 10 hours of content",
    category: "watch_time",
    difficulty: "easy",
    icon: "Eye",
    xpReward: 50,
    fdrReward: 1,
    condition: { type: "totalWatchTime", value: 36000 },
  },
  {
    id: "dedicated_viewer",
    title: "Dedicated Viewer",
    description: "Watch 25 hours of content",
    category: "watch_time",
    difficulty: "medium",
    icon: "PlayCircle",
    xpReward: 100,
    fdrReward: 2,
    condition: { type: "totalWatchTime", value: 90000 },
  },
  {
    id: "dedicated_student",
    title: "Dedicated Student",
    description: "Watch 50 hours of content",
    category: "watch_time",
    difficulty: "medium",
    icon: "Clock",
    xpReward: 200,
    fdrReward: 4,
    condition: { type: "totalWatchTime", value: 180000 },
  },
  {
    id: "knowledge_consumer",
    title: "Knowledge Consumer",
    description: "Watch 100 hours of content",
    category: "watch_time",
    difficulty: "hard",
    icon: "Brain",
    xpReward: 400,
    fdrReward: 8,
    condition: { type: "totalWatchTime", value: 360000 },
  },
  {
    id: "study_machine",
    title: "Study Machine",
    description: "Watch 250 hours of content",
    category: "watch_time",
    difficulty: "extreme",
    icon: "Activity",
    xpReward: 800,
    fdrReward: 16,
    condition: { type: "totalWatchTime", value: 900000 },
  },
  {
    id: "learning_machine",
    title: "Learning Machine",
    description: "Watch 500 hours of content",
    category: "watch_time",
    difficulty: "extreme",
    icon: "Zap",
    xpReward: 1500,
    fdrReward: 30,
    condition: { type: "totalWatchTime", value: 1800000 },
  },
  {
    id: "time_master",
    title: "Time Master",
    description: "Watch 1000 hours of content",
    category: "watch_time",
    difficulty: "legendary",
    icon: "Crown",
    xpReward: 3000,
    fdrReward: 60,
    condition: { type: "totalWatchTime", value: 3600000 },
  },

  // ===== LESSON MILESTONES =====
  {
    id: "lesson_starter",
    title: "Lesson Starter",
    description: "Complete 10 lessons",
    category: "lessons",
    difficulty: "easy",
    icon: "CheckCircle",
    xpReward: 25,
    fdrReward: 0.5,
    condition: { type: "lessonsCompleted", value: 10 },
  },
  {
    id: "lesson_explorer",
    title: "Lesson Explorer",
    description: "Complete 25 lessons",
    category: "lessons",
    difficulty: "easy",
    icon: "Compass",
    xpReward: 50,
    fdrReward: 1,
    condition: { type: "lessonsCompleted", value: 25 },
  },
  {
    id: "lesson_master",
    title: "Lesson Master",
    description: "Complete 50 lessons",
    category: "lessons",
    difficulty: "medium",
    icon: "Award",
    xpReward: 100,
    fdrReward: 2,
    condition: { type: "lessonsCompleted", value: 50 },
  },
  {
    id: "century_learner",
    title: "Century Learner",
    description: "Complete 100 lessons",
    category: "lessons",
    difficulty: "hard",
    icon: "Trophy",
    xpReward: 250,
    fdrReward: 5,
    condition: { type: "lessonsCompleted", value: 100 },
  },
  {
    id: "lesson_veteran",
    title: "Lesson Veteran",
    description: "Complete 250 lessons",
    category: "lessons",
    difficulty: "extreme",
    icon: "Shield",
    xpReward: 500,
    fdrReward: 10,
    condition: { type: "lessonsCompleted", value: 250 },
  },
  {
    id: "lesson_legend",
    title: "Lesson Legend",
    description: "Complete 500 lessons",
    category: "lessons",
    difficulty: "legendary",
    icon: "Crown",
    xpReward: 1000,
    fdrReward: 20,
    condition: { type: "lessonsCompleted", value: 500 },
  },

  // ===== WEB3 SPECIFIC =====
  {
    id: "crypto_curious",
    title: "Crypto Curious",
    description: "Enroll in your first crypto course",
    category: "web3",
    difficulty: "easy",
    icon: "Coins",
    xpReward: 25,
    fdrReward: 1,
    condition: { type: "categoryEnrolled", category: "Crypto" },
  },
  {
    id: "web3_beginner",
    title: "Web3 Beginner",
    description: "Complete your first Web3 course",
    category: "web3",
    difficulty: "easy",
    icon: "Coins",
    xpReward: 50,
    fdrReward: 2,
    condition: { type: "categoryCompleted", category: "Web3" },
  },
  {
    id: "blockchain_enthusiast",
    title: "Blockchain Enthusiast",
    description: "Complete 3 blockchain courses",
    category: "web3",
    difficulty: "medium",
    icon: "Link",
    xpReward: 150,
    fdrReward: 5,
    condition: { type: "categoryCompleted", category: "Blockchain", count: 3 },
  },
  {
    id: "defi_explorer",
    title: "DeFi Explorer",
    description: "Complete your first DeFi course",
    category: "web3",
    difficulty: "medium",
    icon: "TrendingUp",
    xpReward: 100,
    fdrReward: 3,
    condition: { type: "categoryCompleted", category: "DeFi" },
  },
  {
    id: "defi_master",
    title: "DeFi Master",
    description: "Complete 5 DeFi courses",
    category: "web3",
    difficulty: "hard",
    icon: "TrendingUp",
    xpReward: 300,
    fdrReward: 10,
    condition: { type: "categoryCompleted", category: "DeFi", count: 5 },
  },
  {
    id: "nft_enthusiast",
    title: "NFT Enthusiast",
    description: "Complete your first NFT course",
    category: "web3",
    difficulty: "easy",
    icon: "Image",
    xpReward: 75,
    fdrReward: 2,
    condition: { type: "categoryCompleted", category: "NFT" },
  },
  {
    id: "nft_creator",
    title: "NFT Creator",
    description: "Complete 3 NFT courses",
    category: "web3",
    difficulty: "hard",
    icon: "Image",
    xpReward: 250,
    fdrReward: 8,
    condition: { type: "categoryCompleted", category: "NFT", count: 3 },
  },
  {
    id: "smart_contract_novice",
    title: "Smart Contract Novice",
    description: "Complete your first smart contract course",
    category: "web3",
    difficulty: "medium",
    icon: "Code",
    xpReward: 100,
    fdrReward: 3,
    condition: { type: "categoryCompleted", category: "Smart Contracts" },
  },
  {
    id: "smart_contract_dev",
    title: "Smart Contract Developer",
    description: "Complete 5 smart contract courses",
    category: "web3",
    difficulty: "extreme",
    icon: "Code",
    xpReward: 500,
    fdrReward: 15,
    condition: {
      type: "categoryCompleted",
      category: "Smart Contracts",
      count: 5,
    },
  },
  {
    id: "web3_expert",
    title: "Web3 Expert",
    description: "Complete 10 Web3-related courses",
    category: "web3",
    difficulty: "extreme",
    icon: "Sparkles",
    xpReward: 1000,
    fdrReward: 30,
    condition: { type: "web3CoursesCompleted", value: 10 },
  },
  {
    id: "web3_pioneer",
    title: "Web3 Pioneer",
    description: "Complete 20 Web3-related courses",
    category: "web3",
    difficulty: "legendary",
    icon: "Rocket",
    xpReward: 2000,
    fdrReward: 50,
    condition: { type: "web3CoursesCompleted", value: 20 },
  },

  // ===== PERFECTION =====
  {
    id: "perfectionist",
    title: "Perfectionist",
    description: "Complete a course with 100% of lessons finished",
    category: "perfection",
    difficulty: "medium",
    icon: "Star",
    xpReward: 100,
    fdrReward: 3,
    condition: { type: "perfectCourses", value: 1 },
  },
  {
    id: "flawless_three",
    title: "Flawless Three",
    description: "Complete 3 courses with 100% completion",
    category: "perfection",
    difficulty: "hard",
    icon: "Stars",
    xpReward: 200,
    fdrReward: 6,
    condition: { type: "perfectCourses", value: 3 },
  },
  {
    id: "flawless_five",
    title: "Flawless Five",
    description: "Complete 5 courses with 100% completion",
    category: "perfection",
    difficulty: "hard",
    icon: "Award",
    xpReward: 300,
    fdrReward: 10,
    condition: { type: "perfectCourses", value: 5 },
  },
  {
    id: "perfect_ten",
    title: "Perfect Ten",
    description: "Complete 10 courses with 100% completion",
    category: "perfection",
    difficulty: "extreme",
    icon: "Trophy",
    xpReward: 600,
    fdrReward: 20,
    condition: { type: "perfectCourses", value: 10 },
  },

  // ===== SPEED ACHIEVEMENTS =====
  {
    id: "quick_start",
    title: "Quick Start",
    description: "Complete 5 lessons in one day",
    category: "speed",
    difficulty: "medium",
    icon: "Zap",
    xpReward: 75,
    fdrReward: 2,
    condition: { type: "lessonsInDay", value: 5 },
  },
  {
    id: "speed_learner",
    title: "Speed Learner",
    description: "Complete 10 lessons in one day",
    category: "speed",
    difficulty: "hard",
    icon: "Zap",
    xpReward: 150,
    fdrReward: 4,
    condition: { type: "lessonsInDay", value: 10 },
  },
  {
    id: "marathon_student",
    title: "Marathon Student",
    description: "Study for 6 hours in a single day",
    category: "speed",
    difficulty: "hard",
    icon: "Activity",
    xpReward: 200,
    fdrReward: 5,
    condition: { type: "watchTimeInDay", value: 21600 },
  },
  {
    id: "ultra_marathon",
    title: "Ultra Marathon",
    description: "Study for 12 hours in a single day",
    category: "speed",
    difficulty: "extreme",
    icon: "Flame",
    xpReward: 500,
    fdrReward: 15,
    condition: { type: "watchTimeInDay", value: 43200 },
  },

  // ===== COMMUNITY =====
  {
    id: "first_review",
    title: "First Impression",
    description: "Leave your first course review",
    category: "community",
    difficulty: "easy",
    icon: "MessageSquare",
    xpReward: 25,
    fdrReward: 0.5,
    condition: { type: "reviewsWritten", value: 1 },
  },
  {
    id: "helpful_reviewer",
    title: "Helpful Reviewer",
    description: "Leave 5 course reviews",
    category: "community",
    difficulty: "medium",
    icon: "MessageCircle",
    xpReward: 75,
    fdrReward: 2,
    condition: { type: "reviewsWritten", value: 5 },
  },
  {
    id: "critic",
    title: "Critic",
    description: "Leave 10 course reviews",
    category: "community",
    difficulty: "medium",
    icon: "MessageCircle",
    xpReward: 100,
    fdrReward: 3,
    condition: { type: "reviewsWritten", value: 10 },
  },
  {
    id: "super_reviewer",
    title: "Super Reviewer",
    description: "Leave 25 course reviews",
    category: "community",
    difficulty: "hard",
    icon: "Star",
    xpReward: 250,
    fdrReward: 8,
    condition: { type: "reviewsWritten", value: 25 },
  },
  {
    id: "review_master",
    title: "Review Master",
    description: "Leave 50 course reviews",
    category: "community",
    difficulty: "extreme",
    icon: "Award",
    xpReward: 500,
    fdrReward: 15,
    condition: { type: "reviewsWritten", value: 50 },
  },

  // ===== SPENDING ACHIEVEMENTS =====
  {
    id: "first_purchase",
    title: "First Investment",
    description: "Purchase your first course",
    category: "spending",
    difficulty: "easy",
    icon: "ShoppingCart",
    xpReward: 50,
    fdrReward: 1,
    condition: { type: "coursesPurchased", value: 1 },
  },
  {
    id: "growing_library",
    title: "Growing Library",
    description: "Purchase 5 courses",
    category: "spending",
    difficulty: "easy",
    icon: "BookOpen",
    xpReward: 100,
    fdrReward: 2,
    condition: { type: "coursesPurchased", value: 5 },
  },
  {
    id: "course_collector",
    title: "Course Collector",
    description: "Purchase 10 courses",
    category: "spending",
    difficulty: "medium",
    icon: "Package",
    xpReward: 200,
    fdrReward: 5,
    condition: { type: "coursesPurchased", value: 10 },
  },
  {
    id: "library_builder",
    title: "Library Builder",
    description: "Purchase 25 courses",
    category: "spending",
    difficulty: "hard",
    icon: "Library",
    xpReward: 500,
    fdrReward: 15,
    condition: { type: "coursesPurchased", value: 25 },
  },
  {
    id: "knowledge_investor",
    title: "Knowledge Investor",
    description: "Purchase 50 courses",
    category: "spending",
    difficulty: "extreme",
    icon: "TrendingUp",
    xpReward: 1000,
    fdrReward: 30,
    condition: { type: "coursesPurchased", value: 50 },
  },

  // ===== CERTIFICATES =====
  {
    id: "certified_learner",
    title: "Certified Learner",
    description: "Earn your first certificate",
    category: "certificates",
    difficulty: "easy",
    icon: "Award",
    xpReward: 100,
    fdrReward: 3,
    condition: { type: "certificatesEarned", value: 1 },
  },
  {
    id: "certificate_collector",
    title: "Certificate Collector",
    description: "Earn 5 certificates",
    category: "certificates",
    difficulty: "medium",
    icon: "Award",
    xpReward: 250,
    fdrReward: 7,
    condition: { type: "certificatesEarned", value: 5 },
  },
  {
    id: "credentials_master",
    title: "Credentials Master",
    description: "Earn 10 certificates",
    category: "certificates",
    difficulty: "hard",
    icon: "Trophy",
    xpReward: 500,
    fdrReward: 15,
    condition: { type: "certificatesEarned", value: 10 },
  },
  {
    id: "certification_expert",
    title: "Certification Expert",
    description: "Earn 25 certificates",
    category: "certificates",
    difficulty: "extreme",
    icon: "Crown",
    xpReward: 1200,
    fdrReward: 35,
    condition: { type: "certificatesEarned", value: 25 },
  },

  // ===== SPECIAL ACHIEVEMENTS =====
  {
    id: "early_adopter",
    title: "Early Adopter",
    description: "Join the platform in 2025",
    category: "special",
    difficulty: "easy",
    icon: "Sparkles",
    xpReward: 500,
    fdrReward: 10,
    condition: { type: "joinedBefore", date: "2026-01-01" },
  },
  {
    id: "beta_tester",
    title: "Beta Tester",
    description: "Join during beta phase",
    category: "special",
    difficulty: "legendary",
    icon: "Rocket",
    xpReward: 1000,
    fdrReward: 50,
    condition: { type: "joinedBefore", date: "2025-12-01" },
  },
  {
    id: "weekend_warrior",
    title: "Weekend Warrior",
    description: "Complete 10 lessons on weekends",
    category: "special",
    difficulty: "medium",
    icon: "Calendar",
    xpReward: 100,
    fdrReward: 3,
    condition: { type: "weekendLessons", value: 10 },
  },
  {
    id: "night_owl",
    title: "Night Owl",
    description: "Complete 10 lessons after 10 PM",
    category: "special",
    difficulty: "medium",
    icon: "Moon",
    xpReward: 100,
    fdrReward: 3,
    condition: { type: "nightLessons", value: 10 },
  },
  {
    id: "early_bird",
    title: "Early Bird",
    description: "Complete 10 lessons before 8 AM",
    category: "special",
    difficulty: "medium",
    icon: "Sunrise",
    xpReward: 100,
    fdrReward: 3,
    condition: { type: "morningLessons", value: 10 },
  },
  {
    id: "diverse_learner",
    title: "Diverse Learner",
    description: "Complete courses in 5 different categories",
    category: "special",
    difficulty: "hard",
    icon: "Globe",
    xpReward: 300,
    fdrReward: 10,
    condition: { type: "uniqueCategories", value: 5 },
  },
  {
    id: "renaissance_scholar",
    title: "Renaissance Scholar",
    description: "Complete courses in 10 different categories",
    category: "special",
    difficulty: "extreme",
    icon: "Compass",
    xpReward: 750,
    fdrReward: 25,
    condition: { type: "uniqueCategories", value: 10 },
  },
];

module.exports = achievements;
