const categories = {
  "Web3 Development": {
    description: "Build decentralized applications and blockchain solutions",
    subcategories: [
      "Solidity Programming",
      "Smart Contract Development",
      "dApp Development",
      "Web3.js & Ethers.js",
      "Hardhat & Truffle",
      "Frontend Integration",
      "Backend Development",
      "Full Stack Web3",
      "Mobile Web3 Apps",
      "Testing & Debugging",
    ],
    color: "blue",
    icon: "Code",
  },
  "Blockchain Fundamentals": {
    description: "Master the core concepts of blockchain technology",
    subcategories: [
      "Blockchain Basics",
      "Cryptography",
      "Consensus Mechanisms",
      "Network Architecture",
      "Bitcoin Fundamentals",
      "Ethereum Fundamentals",
      "Layer 2 Solutions",
      "Cross-Chain Technology",
      "Blockchain Security",
      "Distributed Systems",
    ],
    color: "purple",
    icon: "Link",
  },
  DeFi: {
    description: "Decentralized Finance protocols and strategies",
    subcategories: [
      "DeFi Basics",
      "Yield Farming",
      "Liquidity Mining",
      "DEX Trading",
      "Lending & Borrowing",
      "Stablecoins",
      "Derivatives",
      "Options Trading",
      "Flash Loans",
      "DeFi Security",
      "Protocol Design",
      "Tokenomics",
    ],
    color: "green",
    icon: "TrendingUp",
  },
  "NFTs & Digital Art": {
    description: "Create, trade, and understand NFTs",
    subcategories: [
      "NFT Basics",
      "NFT Creation",
      "NFT Marketplaces",
      "Digital Art",
      "Generative Art",
      "NFT Marketing",
      "NFT Collection Launch",
      "Smart Contract for NFTs",
      "IPFS & Storage",
      "NFT Utilities",
      "Gaming NFTs",
      "Music NFTs",
    ],
    color: "pink",
    icon: "Image",
  },
  "Smart Contracts": {
    description: "Develop and audit smart contracts",
    subcategories: [
      "Solidity Basics",
      "Advanced Solidity",
      "Smart Contract Patterns",
      "Gas Optimization",
      "Security Best Practices",
      "Contract Upgrades",
      "Testing Frameworks",
      "Auditing Techniques",
      "Formal Verification",
      "ERC Standards",
    ],
    color: "orange",
    icon: "FileCode",
  },
  "Community Building": {
    description: "Build and manage Web3 communities",
    subcategories: [
      "Community Management",
      "Discord Management",
      "Telegram Management",
      "Twitter Spaces",
      "Community Strategy",
      "Engagement Tactics",
      "Moderation",
      "Event Planning",
      "Ambassador Programs",
      "Community Analytics",
      "Collaboration Management",
      "Partnership Development",
    ],
    color: "cyan",
    icon: "Users",
  },
  "Marketing & Growth": {
    description: "Grow your Web3 project",
    subcategories: [
      "Web3 Marketing",
      "Social Media Marketing",
      "Content Marketing",
      "Influencer Marketing",
      "Growth Hacking",
      "SEO for Web3",
      "Email Marketing",
      "Paid Advertising",
      "Brand Building",
      "PR & Media",
      "Go-to-Market Strategy",
      "Community Growth",
    ],
    color: "red",
    icon: "Megaphone",
  },
  "Trading & Investment": {
    description: "Trading strategies and investment analysis",
    subcategories: [
      "Crypto Trading Basics",
      "Technical Analysis",
      "Fundamental Analysis",
      "Chart Patterns",
      "Trading Psychology",
      "Risk Management",
      "Portfolio Management",
      "Altcoin Research",
      "ICO/IDO Analysis",
      "Token Metrics",
      "Market Making",
      "Arbitrage",
    ],
    color: "yellow",
    icon: "LineChart",
  },
  "Security & Auditing": {
    description: "Secure smart contracts and blockchain systems",
    subcategories: [
      "Smart Contract Security",
      "Common Vulnerabilities",
      "Audit Methodology",
      "Security Tools",
      "Bug Bounties",
      "Penetration Testing",
      "Cryptography",
      "Wallet Security",
      "Incident Response",
      "Security Best Practices",
    ],
    color: "red",
    icon: "Shield",
  },
  "DAOs & Governance": {
    description: "Decentralized Autonomous Organizations",
    subcategories: [
      "DAO Basics",
      "Governance Models",
      "Voting Mechanisms",
      "Treasury Management",
      "DAO Tools",
      "Legal Structures",
      "Token Distribution",
      "Proposal Writing",
      "DAO Operations",
      "Conflict Resolution",
    ],
    color: "indigo",
    icon: "Users",
  },
  "Gaming & Metaverse": {
    description: "Build games and metaverse experiences",
    subcategories: [
      "Blockchain Gaming",
      "Game Development",
      "Unity for Web3",
      "Unreal Engine",
      "Metaverse Development",
      "Virtual Worlds",
      "In-Game Economics",
      "Play-to-Earn",
      "Gaming NFTs",
      "Virtual Real Estate",
    ],
    color: "purple",
    icon: "Gamepad",
  },
  "Content Creation": {
    description: "Create engaging Web3 content",
    subcategories: [
      "Video Production",
      "Writing & Blogging",
      "Podcast Production",
      "Twitter Content",
      "YouTube Strategy",
      "Newsletter Creation",
      "Educational Content",
      "Technical Writing",
      "Storytelling",
      "Content Strategy",
    ],
    color: "pink",
    icon: "Video",
  },
  "Business & Entrepreneurship": {
    description: "Build and scale Web3 businesses",
    subcategories: [
      "Web3 Business Models",
      "Startup Strategy",
      "Fundraising",
      "Tokenomics Design",
      "Legal Setup",
      "Team Building",
      "Product Development",
      "Business Development",
      "Partnerships",
      "Scaling Strategies",
    ],
    color: "green",
    icon: "Briefcase",
  },
  "Design & UX": {
    description: "Design beautiful Web3 experiences",
    subcategories: [
      "UI/UX Design",
      "Web3 Design Patterns",
      "Wallet UX",
      "dApp Design",
      "Figma for Web3",
      "User Research",
      "Prototyping",
      "Visual Design",
      "Brand Design",
      "Motion Design",
    ],
    color: "purple",
    icon: "Palette",
  },
  "Legal & Compliance": {
    description: "Navigate Web3 legal landscape",
    subcategories: [
      "Crypto Regulations",
      "Securities Law",
      "Token Classification",
      "Tax Strategy",
      "KYC/AML",
      "Data Privacy",
      "IP Rights",
      "Contract Law",
      "International Compliance",
      "Legal Structures",
    ],
    color: "gray",
    icon: "Scale",
  },
};

module.exports = categories;
